language: php

services: mongodb

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mkdir -p build/logs
  - composer self-update
  - echo 'extension=mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction --prefer-source

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email: "s.toonen@gmail.com"
