language: php

services: mongodb

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - echo 'extension=mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction --prefer-source

after_script:
  - php vendor/bin/coveralls

notifications:
  email: "s.toonen@gmail.com"
